### ISSUE TITLE
urls not working

### ISSUE THREAD

**Issue by chetanchandel31** [facondiaGames/sword-adventure#1]
this tutorial seems like a great learning resource but some of the URLs within the site and in the readme seem to be incorrect and point to error 500 page
![image](https://github.com/facondiaGames/sword-adventure/assets/70325561/8c2f9c4b-d57f-440e-aece-245041877e05)
![image](https://github.com/facondiaGames/sword-adventure/assets/70325561/c58a3764-9715-47b4-b7b4-d17ba1b36fd1)

**Comment by facondiaGames** [comment]
hi @chetanchandel31 , thanks for pointing it out! I've updated the URLs in the README file, they should be working fine now. I've also checked some URLs within the site nicastro.in, and they were working. Can you give me an example of the URLs within the site which are not correct?

**Comment by facondiaGames** [comment]
I've fixed that link too, ty for opening this issue!
